Project.create! name: 'Project 1'
Project.create! name: 'Project 2'
Project.create! name: 'Project 3'
Project.create! name: 'Project 4'
Project.create! name: 'Project 5'
Project.create! name: 'Project 6'
Project.create! name: 'Project 7'